_BASE_: ../oneformer_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2InternImage"
  INTERNIMAGE:
    CHANNELS: 320
    DEPTHS: [6, 6, 32, 6]
    GROUPS: [10, 20, 40, 80]
    WITH_CP: True
    MLP_RATIO: 4.0
    DW_KERNEL_SIZE: 5
    LEVEL2_POST_NORM_BLOCK_IDS: [5, 11, 17, 23, 29]
  WEIGHTS: "internimage_h_jointto22k_384.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  ONE_FORMER:
    NUM_OBJECT_QUERIES: 250
TEST:
  DETECTIONS_PER_IMAGE: 250